
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "b1d13a3add7515f53081aaba7143720907414073",
 "version": "0+untagged.1706.gb1d13a3.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
